### 获取所有用户
GET http://localhost:8080/users

### 根据ID获取用户
GET http://localhost:8080/users/2

### 创建用户
POST http://localhost:8080/users
Content-Type: application/json

{"id":4,"name":"Svelte","email":"svelte@dev.com"}

### 删除用户
DELETE http://localhost:8080/users/1
